config/routes.rb
Noar::Application.routes.draw do
  

  root 'picks#new'
  get "logout", to:"users#logout", as:"logout"
  
  resources :users

  resources :picks
end

app/models/movie.rb
class Movie
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  #has_many :reviews, class_name: "ReviewedProfile", inverse_of: :profile

  field :title, type: String
  field :imdb_id, type: String
  field :director, type: String
  field :stars, type: Array

  field :image_url, type: String
  field :summary, type: String
  field :genre, type: String
  field :year, type: String

  field :normalized_score, type: Float, default: 0.0

  field :review_count, type: Integer, default:0

  @@High_Review_Threshold = 5

  validates_presence_of :title

  def self.from_seed_file
    logger.debug "new movie profile requested"
    begin
      chosen_line = nil
      path = Rails.root.join('public').join('movie_titles.json')
      File.foreach(path).each_with_index do |line, number|
        chosen_line = line if rand < 1.0/(number+1)
      end

      movie_h = JSON.parse chosen_line
      raise "already stored" if Movie.where(movie_h).first

      out = Movie.new(movie_h)
      out.augment_from_omdb
    rescue
      return nil
    end

    logger.info "created #{out.title}"
    return out
  end


  def self.least_reviewed(options={})
    if(exc = options[:exclude])
      excids = exc.map{|r| r._id}
      item = Movie.not_in(_id: excids).asc(:review_count).limit(1).first
    else
      item = Movie.asc(:review_count).limit(1).first
    end

    #can remove - specific to seed file
    if(!item || item.review_count > @@High_Review_Threshold)
      return nil if(options[:no_new_seeds])
      m = Movie.from_seed_file
      item = m if m && m.save
    end

    return item
  end

  def was_reviewed
    self.review_count += 1
    save
  end

  def self.from_name(name, options={})
    m = Movie.new
    m.title = name

    options.each{|k,v| m.send(k+"=",v)}
    m.augment_from_omdb
    return m
  end


  @@Movie_Lookup_Base = "www.omdbapi.com"
  def augment_from_omdb(options={})
    mh = Util.json_api_get(@@Movie_Lookup_Base,{t:title, y:year})
    self.genre = mh["Genre"]
    self.year = mh["Year"]
    self.director = mh["Director"]
    self.summary = mh["Plot"]
    self.stars = mh["Actors"].split /,\s*/
    self.imdb_id = mh["imdbID"]
    self.image_url = mh["Poster"]
    return mh["imdbID"] != nil
  end


end

app/models/reviewed_profile.rb
class ReviewedProfile
  include Mongoid::Document
  include Utiloid

  embedded_in :user #, inverse_of: :reviewed_profiles
  references_doc :profile, class_name: "Movie"

  field :score, type: Float, default:0.0

  #cached values
  field :review_count, type: Integer, default:0
  field :title, type: String

  field :beats, type: Array, default:[] #id list
  field :beaten_by, type: Array, default:[] #id list



  def initialize(profile=nil)
    super(nil)
    if profile
      self.profile = profile
      self.score = profile.normalized_score
      self.title = profile.title
    end
  end

  def beat(other)
    spread = 10.0 / (1.0 + Math.exp((self.score - other.score)/10.0))
    self.was_reviewed(other,spread)
    other.was_reviewed(self,-spread)
  end

  def was_reviewed(other, spread)
    self.review_count += 1
    self.score += spread
    (spread > 0 ? self.beats : self.beaten_by) << other.profile_id
    #puts "*************** beats:#{beats} beaten_by:#{beaten_by}"
    save!
  end



end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  field :name,   type:  String
  field :email,  type:  String

  embeds_many :reviewed_profiles, class_name:"ReviewedProfile" #, inverse_of: :user

  @@AddNewProfileChance = 0.333

  def prime_reviews(n=3)
    n.times {add_new_profile_for_review}
    raise "couldn't add 3 profiles!" if reviewed_profiles.length < 3
  end

  def next_choice_pair
    initial = reviewed_profiles.min_by{|rp| rp.review_count}

    #let [exclude] be the set of all reviewed movies that have been paired with [initial], along with [initial] itself
    exclude = Set.new([initial.profile_id])
    initial.beats.each  {|pid| exclude.add(pid)}
    initial.beaten_by.each  {|pid| exclude.add(pid)}

    possible_ids = (Set.new(reviewed_profiles.map{|rp| rp.profile_id}) - exclude).to_a

    #if they are unlucky enough to exhaust all pairs without ever getting new profiles added, handle that
    if possible_ids.length == 0
      logger.warn "User #{_id} ran out of pairs"
      raise Exception.new("Needed new profile couln't be created") unless new_rp = add_new_profile_for_review
      return [initial.profile, new_rp.profile]
    end

    return [initial.profile, rprofile_from_pid(possible_ids.sample).profile]
  end

  def add_pick(winner_id, runnerup_id, options={})
    winner_rp = rprofile_from_pid(winner_id)
    runnerup_rp = rprofile_from_pid(runnerup_id)

    raise Exception.new "Profile(s) not in review." unless winner_rp && runnerup_rp

    winner_rp.beat(runnerup_rp)
    save!

    #chance of adding a new profile to the menu
    if !options[:no_new_profile] and rand > @@AddNewProfileChance
      new_rp = self.add_new_profile_for_review
      logger.warn("new profile was to be added, but couldn't be created") unless new_rp
    end

    return true
  end

  def profiles_beatten_by(pid)
    rp = rprofile_from_pid(pid)
    rp.beats.clone
  end

  def profiles_that_beat(pid)
    rp = rprofile_from_pid(pid)
    rp.beaten_by.clone
  end

  def add_new_profile_for_review
    profile = Movie.least_reviewed(exclude: self.reviewed_profiles.map{|rp| rp.profile})
    if profile
      profile.was_reviewed
    else
      return nil
    end

    rprofile = ReviewedProfile.new(profile)
    reviewed_profiles << rprofile
    save!
    return rprofile
  end

  def pick_count
    reviewed_profiles.inject(0){|memo, rp| memo+rp.beats.length}
  end

  def rprofile_from_pid(pid)
    ind = self.reviewed_profiles.rindex{|rp| rp.profile_id.to_s == pid.to_s}
    ind ? self.reviewed_profiles[ind] : nil
  end

end

app/models/util.rb
class Util
require 'net/http'
require 'net/https'
def self.json_api_get base_URI, params=nil, cookie=""

    response = {raw: (Net::HTTP.get_response(base_URI,"/"+Util.hash_to_qs(params))) }
    #puts "cookie#{cookie.inspect}" if cookie
    #request = Net::HTTP::Get.new(  "#{uri.request_uri}#{Util.hash_to_qs params}" , {"Cookie"=>cookie} )
    
    #response = {:raw=>http.request(request)}
    #response[:cookie] = response[:raw].response['set-cookie'] if response[:raw].response

    begin
      response[:parsed] = JSON.parse response[:raw].body
    rescue
      puts "parse failed"
      puts response[:raw].body.inspect
    end
    return response[:parsed]
  end
  
  def self.hash_to_qs hash, options=nil
    str = ""
    return str if !hash
    str += "?" if !(options && options[:append])
    hash.each_pair do |key,value|
      str += "#{key}=#{URI.encode(value.to_s)}&"
    end
    return str.chop!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  protected
  def get_user
    unless (uid = session[:user_id]) && (@user = User.find(uid) )
      redirect_to controller: :users, action: :new
    end
  end
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
  before_filter :get_user
  
  #[GET] /pick/new
  def new
    @pick_count = @user.pick_count
    @choice_a, @choice_b = @user.next_choice_pair
  end
  
  #[POST] /pick
  def create
    winner_id = params[:pick]
    runnerup_id = params[:runnerup] || (params[:both].values - [winner_id]).first

    if @user.add_pick(winner_id, runnerup_id)
      flash[:notice] = "Pick saved."
      redirect_to action: :new
    else
      flash[:notice] = "Pick save failed."
      flash[:notice_type] = :error
      render :new
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :get_user, except: [:new, :create]

  #[GET] /user/new
  def new
    @user = User.new
    
  end
  
  #[POST] /user/
  def create

    uprm = params[:user]
    name = uprm[:name].downcase
    unless @user = User.where(name: name).first
      @user = User.create!(name: name, email:uprm[:email])
      @user.prime_reviews(10)
    end

    session[:name] = @user.name
    session[:user_id] = @user._id

    redirect_to controller: :picks, action: :new
  end

  def logout
    session.delete(:name)
    session.delete(:user_id)

    redirect_to action: :new
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] -%>
    <% css_class = notice + (flash[:notice_class] || "" ) -%>
    <%= content_tag :section, flash[:notice], class: css_class %>
<% end -%>

app/views/layouts/_header.html.erb
<header>
  <% if session[:user_id] %>
      <div>
        Logged in as <%= session[:name] %>
      </div>

      <div>
        <%= link_to "Log Out", controller: :users, action: :logout %>
      </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Picker</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<%= yield %>

</body>
</html>

app/views/picks/new.html.erb
<% if @pick_count > 0 %>
<h3><%= @pick_count %> picks made so far...</h3>
<% end %>

<%= render "layouts/flash" %>

<%= form_tag picks_path do %>
    <div class="form-header">
      <%= submit_tag "Save", class:"choice-submit-button" %>
      <h1>Pick One...</h1>
    </div>

    <% [@choice_a, @choice_b].each_with_index do |choice, i| %>
        <article class="choice">
        <%= radio_button_tag "pick" , choice._id, false, class:"profile-radio" %>
        <label for="pick_<%=choice._id%>">

            <h3 class="movie-title"><%= choice.title %></h3>

            <p class="movie-summary">
                <%= choice.summary %>
            </p>

            <%= image_tag choice.image_url, class:"movie-poster", alt:"" %>


          <ul class="movie-attributes">
              <li>
                <div class="movie-attribute name">
                  Genre
                </div>
                <div class="movie-attribute value">
                  <%= choice.genre %>
                </div>
              </li>
    
              <li>
                <div class="movie-attribute name">
                    Director
                </div>
                <div class="movie-attribute value">
                    <%= choice.director %>
                </div>
              </li>
              <li>
                <div class="movie-attribute name">
                    Stars
                </div>
                <div class="movie-attribute value">
                    <%= choice.stars.join ", " %>
                </div>
              </li>
    
            </ul>
            <div class="clearfix"></div>
        </label>
        </article>
        <%= hidden_field_tag "both[#{i}]", choice.id %>
    <% end %>
<% end %>

<script language="JavaScript">


  function checkRadios(){
      var radios = document.getElementsByClassName("profile-radio");
      var anyClicked = false;
      for(var i=0;i<radios.length;i++) anyClicked = anyClicked || radios[i].checked;
      var button = document.getElementsByClassName("choice-submit-button")[0].disabled = !anyClicked;
  }

  var radios = document.getElementsByClassName("profile-radio");
  for(var i=0;i<radios.length;i++)
    radios[i].onchange = checkRadios;

  checkRadios();
</script>

app/views/users/new.html.erb
<section class="centered-form">
	<% if flash[:notice]%>
		<div class="notice">
			<%=flash[notice]%>
		</div>
	<% end %>
	<%= form_for @user do |f| %>
		<h2>What's your name?</h2>
		<%= f.text_field :name%>
		<h3>Can I have your email too?</h3>
		<%= f.text_field :email%>
		<div>
		    <%= f.submit "Go", class:"choice-submit-button" %>
        </div>
	<% end %>
</section>